name: alajo_os
description: A smart offline-first mobile assistant for traditional thrift savings collectors (Alajo) in Nigeria.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.7
  sqflite: ^2.3.0
  path: ^1.9.0
  mobile_scanner: ^5.1.1
  speech_to_text: ^6.1.1
  qr_flutter: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
